# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactional_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
