# Generated by Django 2.1.15 on 2019-12-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactional_mail', '0002_auto_20180313_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredEmailType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('transactional_mail.sentmail',),
        ),
    ]
